# Generated by Django 6.0 on 2025-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('bought', 'bought'), ('ignored', 'ignored')], default='active', max_length=100),
        ),
    ]
