# Generated by Django 6.0 on 2025-12-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baskets',
            new_name='Basket',
        ),
    ]
