# Generated by Django 6.0 on 2025-12-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_rename_baskets_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Completed', 'completed'), ('Open', 'open')], default='Pending', max_length=100),
        ),
    ]
