# Generated by Django 6.0 on 2025-12-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_alter_basket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending_KD'), ('Completed', 'Completed_KD'), ('Open', 'Open_KD')], default='Pending', max_length=100),
        ),
    ]
